baseURL = 'https://www.computational-quantum.science/'
languageCode = 'en-us'
title = 'Computational Quantum Science'
relativeUrl = true
summaryLength = 120

[params]
  address = "Forschungszentrum Jülich GmbH | PGI-8 | Wilhelm-Johnen-Straße | 52425 Jülich"
  phone = "+49 2461/61-96965"
[params.author]
  name = "Markus Schmitt"
  email = "bWFya3VzLnNjaG1pdHRAZnotanVlbGljaC5kZQ=="
[params.publications]
  startYear = 2015


[taxonomies]
  tag = "tags"
  category = "categories"
  example = "examples"
